<?php namespace ProcessWire;

/**
 * ProcessWire Color Inputfield
 *
 * @author Christoph Thelen aka @kixe 2017/07/03
 * @copyright © 2017 Christoph Thelen
 * @license Licensed under GNU/GPL v3
 * @link https://processwire.com/talk/topic/...
 * @version 1.1.4
 *
 * @since 1.0.1 2017/07/05 - better validation, spectrum options modifiable
 * @since 1.0.2 2017/07/09 - added default value option
 * @since 1.0.3 2017/07/09 - added option for custom javascript
 * @since 1.0.4 2017/08/18 - made # optional for input (pattern attribute)
 * @since 1.0.5 2017/08/28 - optimized default color handling, added output format option array()
 * @since 1.0.6 2017/12/17 - modified render() for usage in modules config
 * @since 1.0.7 2017/12/17 - sync version number to fieldtype
 * @since 1.0.8 2018/08/31 - added functions getTextColor() convertColorName()
 * @since 1.0.9 2019/01/12 - fixed number format bug for rgba() and hsla() alpha channel if comma is forced as decimal separator by locale settings, added data-input-type attribute for better JS handling
 * @since 1.1.0 2019/08/12 - better input check formatColorString()
 * @since 1.1.1 2019/09/01 - fixed bug missing opacity if 0
 * @since 1.1.2 2019/09/04 - fixed bug #5 FieldtypeColor index typo in var in function RGB2HSL() thanks to @junoforno
 * @since 1.1.3 2019/10/10 - fixed bug #1 InputfieldColor - remove pattern attribute if spectrum color picker is used to prevent error in Chrome
 * @since 1.1.4 2020/05/15 switched to PrpcessWirte namespace
 *
 * made for ProcessWire 3.x by Ryan Cramer
 * https://processwire.com
 * 
 * @todo
 * - include i18n support provided by spectrum color picker
 * 
 */

class InputfieldColor extends Inputfield {
	
	public static function getModuleInfo() {
		return array(
			'title' => __('Color', __FILE__), // Module Title
			'summary' => __('Inputfield for colors', __FILE__), // Module Summary
			'version' => 114,
			'href' => 'https://processwire.com/talk/topic/16679-fieldtypecolor/'
			);
	}

	/**
	 * Construct
	 * 
	 * @throws WireException
	 * 
	 */
	public function __construct() {
		parent::__construct();
		$this->set('icon', 'paint-brush');
		$this->setAttribute('type', 'text'); 
		$this->setAttribute('size', 10); 
		$this->setAttribute('placeholder', '#000000');
		$this->setAttribute('pattern', '(#?[a-fA-F\d]{6})?');
	}

	public function init() {
		$this->inputType = 0;
		$this->spectrum =  '';
		$this->initJS = '';
		$this->fileJS = '';
		$this->fileCSS = '';
		$this->jqueryCore = 0;
		$this->jqueryUI = 0;
		$this->alpha = 0;
		parent::init();
	}

	/**
	 * Called before the render method
	 * checking for SpectrumColorPicker
	 * 
	 * @param Inputfield $parent
	 * @param bool $renderValueMode
	 * @return $this
	 *
	 */
	public function renderReady(Inputfield $parent = null, $renderValueMode = false) {
		$url = $this->config->urls->get('InputfieldColor');
		switch ($this->inputType) {	
			case 3:
				$this->wire('modules')->get('JqueryCore');
				$this->config->scripts->add($url . 'spectrum/spectrum.js');
				$this->config->styles->add($url . 'spectrum/spectrum.css');
				break;
			case 4:
				if ($this->jqueryCore) $this->wire('modules')->get('JqueryCore');
				if ($this->jqueryUI) $this->wire('modules')->get('JqueryUI');
				if ($this->fileJS) $this->config->scripts->add($url . $this->fileJS);
				if ($this->fileCSS) $this->config->styles->add($url . $this->fileCSS);
			break;
		}
		parent::renderReady($parent, $renderValueMode); 
	}

	/**
	 * get textcolor (light or dark) corresponding to the background for better contrast
	 * 
	 * @param int/string $bgColor expecting string or int with 6 (24bit) or 8 (32bit) digits with or without leading '#'
	 * @param int/string $textColorLight default: '#fff' (white)
	 * @param int/string $textColorDark	default: '#000' (black)
	 * @return string $color light or dark
	 *
	 */
	public function getTextColor($bgColor, $textColorLight = '#fff', $textColorDark = '#000') {
		if (!is_string($bgColor)) return $textColorDark;
		else if (!ctype_xdigit(ltrim($bgColor, '#'))) {
			$bgColor = $this->convertColorName($bgColor);
			if (false === $bgColor) return $textColorDark;
		}
		$bgColor = ltrim($bgColor, '#');
		$bgColor = str_pad($bgColor,8,'f',STR_PAD_LEFT);
		$ARGB = array_map('hexdec', str_split($bgColor, 2));
		$opacity = round($ARGB[0] / 255, 2);
		if ($opacity < 0.45) return $textColorDark;
		return ($ARGB[1]+6*$ARGB[2]+$ARGB[3])*3/8 > 460?  $textColorDark : $textColorLight;
	}

	/**
	 * convert color name (hex -> html, html -> hex)
	 * 
	 * @param $color
	 * @param $to convert to 'hex' or 'html'
	 * @return bool/ string
	 *
	 */
	public function convertColorName($color, $to = 'hex') {
		$colorArray = $this->getX11ColorArray();
		if ($to = 'hex') {
			$key = array_search($color, array_column($colorArray, 0));
			return empty($colorArray[$key][1])? false : $colorArray[$key][1];
		}
		else if ($to = 'html') {
			$key = array_search($color, array_column($colorArray, 1));
			return empty($colorArray[$key][0])? false : $colorArray[$key][0];
		}
		return false;
	}

	/**
	 * get multiple array with html color names and corresponding hex codes and rgb values
	 * 
	 * @param $domain
	 * @param $path file path
	 * @return boolean
	 *
	 */
	protected function getX11ColorArray() {
		$path = __DIR__ .'/x11color.txt';
		if (!file_exists($path)) throw new WireException("Missing file " . $path);
		$array = file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
		if ($array === false) throw new WireException("Failed to open file: $path");
		return array_map(function($e) {
			return explode("\t", $e);
		}, $array);
	}

	public function ___render() {
		if ($this->value === "" && strlen($this->initValue)) $this->value = $this->initValue;
		if (!$this->value) $this->value = null;

		if ($this->value) {
			$this->value = str_pad(ltrim($this->value, '#'),8,'f',STR_PAD_LEFT);
			$color32 = "#".$this->value;
			$color24 = $bgColor = "#".substr($this->value,2,6);		
			$value = array_map('hexdec', str_split($this->value, 2));
		} else {
			$color32 = $color24 = null;
			$value = array(255,255,255,255);
			$bgColor = '#fff';
		}

		$opacity = round($value[0] / 255, 2);
		$opacity = $opacity? rtrim(number_format($opacity, 2, '.', ''),'.0') : '0';

		$textColor = $this->getTextColor($this->value);
		$rgba = "rgba($value[1], $value[2], $value[3], $opacity)";
		$this->attr('value', $color24);
		$this->attr('data-input-type', $this->inputType);

		switch ($this->inputType) {	
			case 0:		
				$this->attr('type', 'color');
				break;
			case 1:
				$this->attr('style', "color: $textColor; background: $bgColor;");
				break;
			case 2:
				$this->alpha = 1;
				$this->attr('value', $color32);
				$this->attr('style', "color: $textColor; background: $bgColor; background-image: linear-gradient($rgba, $rgba), url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAIAAADZF8uwAAAAGUlEQVQYV2M4gwH+YwCGIasIUwhT25BVBADtzYNYrHvv4gAAAABJRU5ErkJggg==');");
				$this->attr('placeholder', '#ff000000');
				$this->attr('pattern', '(#?[a-fA-F\d]{8})?');
				break;
			case 3:
				$this->alpha = 1;
				if (!$color32) $color32 = '#00000000';
				$this->attr('value', $color32);
				$this->attr('placeholder', '#ff000000');
				$this->removeAttr('pattern');
				break;
			case 4:
				if ($this->alpha) $this->attr('value', $color32);
				else $this->attr('value', $color24);		
		}

		$attrs = $this->getAttributes();

		$out = "<input " . $this->getAttributesString($attrs) . " />";
		if( $this->inputType == 3) {
			$options = $this->spectrum? str_replace(array(",\n","\n"),", ", trim($this->spectrum,",\t\n\r\0\x0B")).',' : '';
			$value = $color32? $color32 : null;
			$out .= "<script>
				$(\"#$this->id\").spectrum({
				    $options
				    color: \"$value\",
				    change: function(color) {
				    	this.value = color.toHex8String(); 
				    }
				});
			</script>
			";
		}
		if( $this->inputType == 4) {
			$value = $color32? $color32 : null;
			if ($this->initJS) {
				$initJS = str_replace(array("{value}","{id}"), array($color24, $this->id), $this->initJS);
				$out .= "<script>
					$initJS
				</script>
				";
			}
		}
		return $out; 
	}

	public function ___processInput(WireInputData $input) {
		parent::___processInput($input);
		$value = $this->attr('value');
		if (!$value) return $this;		
		$pattern = $this->alpha? '/#?[a-fA-F\d]{8}/' : '/#?[a-fA-F\d]{6}/';
		if(!preg_match($pattern, $value)) $this->error("Does not match required pattern: $pattern.");
		return $this;

	}

	public function getConfigInputfields() {
		$inputfields = parent::getConfigInputfields();

		$f = $this->wire('modules')->get('InputfieldRadios');
		$f->attr('name', 'inputType');
		$f->label = $this->_('Inputfieldtype'); 
		$f->addOption(0, $this->_('Inputfield type=\'color\' (HTML5 - limited browser support)')); 
		$f->addOption(1, $this->_('Inputfield type=\'text\' expects 24bit hexcode strings'));
		$f->addOption(2, $this->_('Inputfield type=\'text\' expects 32bit hexcode strings (alpha channel)'));  
		$f->addOption(3, $this->_('Inputfield with Spectrum Color Picker (JavaScript)')); 
		$f->addOption(4, $this->_('Inputfield type=\'text\' with custom JavaScript and/or CSS')); 
		$f->attr('value', $this->inputType);
		$f->description = $this->_('');
		$f->columnWidth = 50;
		$inputfields->add($f);

		$f = $this->wire('modules')->get('InputfieldTextarea');
		$f->attr('name', 'spectrum');
		$f->attr('rows', 10);
		$f->label = $this->_('Color Picker Options'); 
		$f->attr('value', $this->spectrum);
		$f->description = $this->_('Set or modify options for the **Spectrum Color Picker**. [Read more ...](https://bgrins.github.io/spectrum/#options)');
		$f->notes = $this->_("One option per line in the format: 'option: value'. The options: 'color' and 'change' are used by the system and not modifiable.");
		$f->columnWidth = 50;
		$f->showIf = "inputType=3";
		$inputfields->add($f);

		$f = $this->wire('modules')->get('InputfieldTextarea');
		$f->attr('name', 'initJS');
		$f->attr('rows', 3);
		$f->label = $this->_('Initial JS'); 
		$f->attr('value', $this->initJS);
		$f->description = $this->_('JavaScript code initiating your custom JS color picker. Use {id} and {value} as placeholders for the related field attributes in your selector');
		$f->notes = sprintf($this->_('{id} will be replaced by the string "%s"'), $this->id);
		$f->columnWidth = 33;
		$f->showIf = "inputType=4";
		$f->requiredIf = "inputType=4";
		$inputfields->add($f);

		$rootUrl = $this->config->urls->get('InputfieldColor');

		$f = $this->wire('modules')->get('InputfieldURL');
		$f->attr('name', 'fileJS');
		$f->label = $this->_('Include JS File'); 
		$f->attr('value', $this->fileJS);
		$f->description = $this->_('Set the path to your custom JavaScript file.');
		$f->notes = sprintf($this->_('URL string relative to "%s"'), $rootUrl);
		$f->columnWidth = 34;
		$f->showIf = "inputType=4";
		$f->requiredIf = "inputType=4";
		$inputfields->add($f);

		$f = $this->wire('modules')->get('InputfieldURL');
		$f->attr('name', 'fileCSS');
		$f->label = $this->_('Include CSS File'); 
		$f->attr('value', $this->fileCSS);
		$f->description = $this->_('Set the path to your custom stylesheet file.');
		$f->notes = sprintf($this->_('URL string relative to "%s"'), $rootUrl);
		$f->columnWidth = 33;
		$f->showIf = "inputType=4";
		$f->requiredIf = "inputType=4";
		$inputfields->add($f);

		$f = $this->modules->get('InputfieldCheckbox');
        $f->attr('name', 'jqueryCore'); 
        $f->label = __('Enable JqueryCore');
        $f->attr('checked', $this->jqueryCore ? 'checked' : '' );
        $f->columnWidth = 33; 
        $f->showIf = "inputType=4";
        $inputfields->append($f);

		$f = $this->modules->get('InputfieldCheckbox');
        $f->attr('name', 'jqueryUI'); 
        $f->label = __('Enable JqueryUI');
        $f->attr('checked', $this->jqueryUI ? 'checked' : '' );
        $f->columnWidth = 34; 
        $f->showIf = "inputType=4";
        $inputfields->append($f);

		$f = $this->modules->get('InputfieldRadios');
        $f->attr('name', 'alpha'); 
        $f->addOption(0, $this->_('6 digits "#ff0000"'));
        $f->addOption(1, $this->_('8 digits "#ffff0000" (leading alpha channel)'));
        $f->label = __('Select value type');
        $f->attr('value', $this->alpha);
        $f->columnWidth = 33; 
        $f->showIf = "inputType=4";
        $inputfields->append($f);

        return $inputfields; 
	}
}
