<?php

/**
 * ProcessWire Color Inputfield
 *
 * @author Christoph Thelen aka @kixe 2017/07/03
 * @copyright © 2017 Christoph Thelen
 * @license 
 * @link https://processwire.com/talk/topic/...
 * @version 1.0.0
 * @since 1.0.0 init - 2017/07/03
 * 
 * made for ProcessWire 2.x, 3.x, Copyright 2016 by Ryan Cramer
 * https://processwire.com
 * @todo
 * - include i18n support provided by spectrum color picker
 * - include custom JS solution
 * 
 */

class InputfieldColor extends Inputfield {
	
	public static function getModuleInfo() {
		return array(
			'title' => __('Color', __FILE__), // Module Title
			'summary' => __('Inputfield for colors', __FILE__), // Module Summary
			'version' => 100,
			);
	}

	public function init() {
		$this->set('spectrum', false); 
		$this->inputType = 0;
		parent::init();
	}

	/**
	 * Called before the render method
	 * checking for SpectrumColorPicker
	 * 
	 * @param Inputfield $parent
	 * @param bool $renderValueMode
	 * @return $this
	 *
	 */
	public function renderReady(Inputfield $parent = null, $renderValueMode = false) {

		if ($this->inputType == 3) {	
			$url = $this->config->urls->get('InputfieldColor');
			$this->wire('modules')->get('JqueryCore');
			// $this->wire('modules')->get('JqueryUI');
			$this->config->scripts->add($url . 'spectrum/spectrum.js');
			$this->config->styles->add($url . 'spectrum/spectrum.css');
		}

		parent::renderReady($parent, $renderValueMode); 
	}

	public function ___render() {
		$fc = $this->wire('modules')->get('FieldtypeColor');
		$color32 = "#".$this->value;
		$color24 = "#".substr($this->value,2,6);
		$value = array_map('hexdec', str_split($this->value, 2));
		$textColor = (2*$value[1]+5*$value[2]+$value[3])*3/8 > 560? '#000':'#fff';
		$opacity = round($value[0] / 255, 2);
		$rgba = "rgba($value[1],$value[2],$value[3],$opacity)";
		$this->attr('value', $color24);

		switch ($this->inputType) {	
			case 0:		
				$this->attr('type', 'color');
				$this->attr('style', 'height:2em; padding:0;');
				break;
			case 1:		
				$this->attr('type', 'text');
				$this->attr('style', "color: $textColor; background: $color24;");
				break;
			case 2:		
				$this->attr('type', 'text');
				$this->attr('value', $color32);
				$this->attr('style', "color: #000; background: #ddd; background-image: linear-gradient($rgba, $rgba), url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAIAAADZF8uwAAAAGUlEQVQYV2M4gwH+YwCGIasIUwhT25BVBADtzYNYrHvv4gAAAABJRU5ErkJggg==');");
				break;
			case 3:		
				$this->attr('type', 'text');
				$this->attr('value', $color32);
				break;
		}

		$attrs = $this->getAttributes();	
		
		if (!strlen($attrs['value']) && strlen($this->initValue)) {
			$attrs['value'] = (int) $this->initValue;
		}

		$out = "<input " . $this->getAttributesString($attrs) . " />";
		if( $this->inputType == 3) $out .= "<script>
				$(\"#$this->id\").spectrum({
					preferredFormat: \"hex\",
				    color: \"$color32\",
				    // color: tinycolor,
				    showAlpha: true,
				    showInput: true,
				    change: function(color) {
				    	this.value = color.toHex8String(); 
				    }
				});
			</script>
		";
		return $out; 
	}

	public function getConfigInputfields() {
		$inputfields = parent::getConfigInputfields();

		$f = $this->wire('modules')->get('InputfieldRadios');
		$f->attr('name', 'inputType');
		$f->label = $this->_('Inputfieldtype'); 
		$f->addOption(0, $this->_('Inputfield type=\'color\' (HTML5)')); 
		$f->addOption(1, $this->_('Inputfield type=\'text\' expects 24bit hexcode strings'));
		$f->addOption(2, $this->_('Inputfield type=\'text\' expects 32bit hexcode strings (alpha channel)'));  
		$f->addOption(3, $this->_('Inputfield with Spectrum Color Picker (Javascript)')); 
		$f->attr('value', $this->inputType);
		$f->description = $this->_('');
		$inputfields->add($f);

		return $inputfields; 
	}
}
